// Package microvm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package microvm

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for DirectoryObject.
const (
	DirectoryObjectDirectory DirectoryObject = "directory"
)

// Valid indicates whether the value is a known member of the DirectoryObject enum.
func (e DirectoryObject) Valid() bool {
	switch e {
	case DirectoryObjectDirectory:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ErrorTypeApiError            ErrorType = "api_error"
	ErrorTypeAuthenticationError ErrorType = "authentication_error"
	ErrorTypeCapacityError       ErrorType = "capacity_error"
	ErrorTypeIdempotencyError    ErrorType = "idempotency_error"
	ErrorTypeInvalidRequestError ErrorType = "invalid_request_error"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ErrorTypeApiError:
		return true
	case ErrorTypeAuthenticationError:
		return true
	case ErrorTypeCapacityError:
		return true
	case ErrorTypeIdempotencyError:
		return true
	case ErrorTypeInvalidRequestError:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionObject.
const (
	ExecutionObjectExecution ExecutionObject = "execution"
)

// Valid indicates whether the value is a known member of the ExecutionObject enum.
func (e ExecutionObject) Valid() bool {
	switch e {
	case ExecutionObjectExecution:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionListObject.
const (
	ExecutionListObjectList ExecutionListObject = "list"
)

// Valid indicates whether the value is a known member of the ExecutionListObject enum.
func (e ExecutionListObject) Valid() bool {
	switch e {
	case ExecutionListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionStatus.
const (
	ExecutionStatusCanceled ExecutionStatus = "canceled"
	ExecutionStatusExited   ExecutionStatus = "exited"
	ExecutionStatusFailed   ExecutionStatus = "failed"
	ExecutionStatusRunning  ExecutionStatus = "running"
	ExecutionStatusTimedOut ExecutionStatus = "timed_out"
	ExecutionStatusVanished ExecutionStatus = "vanished"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case ExecutionStatusCanceled:
		return true
	case ExecutionStatusExited:
		return true
	case ExecutionStatusFailed:
		return true
	case ExecutionStatusRunning:
		return true
	case ExecutionStatusTimedOut:
		return true
	case ExecutionStatusVanished:
		return true
	default:
		return false
	}
}

// Defines values for FileObject.
const (
	FileObjectFile FileObject = "file"
)

// Valid indicates whether the value is a known member of the FileObject enum.
func (e FileObject) Valid() bool {
	switch e {
	case FileObjectFile:
		return true
	default:
		return false
	}
}

// Defines values for FileListObject.
const (
	FileListObjectList FileListObject = "list"
)

// Valid indicates whether the value is a known member of the FileListObject enum.
func (e FileListObject) Valid() bool {
	switch e {
	case FileListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for FrameObject.
const (
	FrameObjectFrame FrameObject = "frame"
)

// Valid indicates whether the value is a known member of the FrameObject enum.
func (e FrameObject) Valid() bool {
	switch e {
	case FrameObjectFrame:
		return true
	default:
		return false
	}
}

// Defines values for FrameType.
const (
	FrameTypeError   FrameType = "error"
	FrameTypeExit    FrameType = "exit"
	FrameTypeStarted FrameType = "started"
	FrameTypeStderr  FrameType = "stderr"
	FrameTypeStdout  FrameType = "stdout"
)

// Valid indicates whether the value is a known member of the FrameType enum.
func (e FrameType) Valid() bool {
	switch e {
	case FrameTypeError:
		return true
	case FrameTypeExit:
		return true
	case FrameTypeStarted:
		return true
	case FrameTypeStderr:
		return true
	case FrameTypeStdout:
		return true
	default:
		return false
	}
}

// Defines values for HealthObject.
const (
	HealthObjectHealth HealthObject = "health"
)

// Valid indicates whether the value is a known member of the HealthObject enum.
func (e HealthObject) Valid() bool {
	switch e {
	case HealthObjectHealth:
		return true
	default:
		return false
	}
}

// Defines values for ImageObject.
const (
	ImageObjectImage ImageObject = "image"
)

// Valid indicates whether the value is a known member of the ImageObject enum.
func (e ImageObject) Valid() bool {
	switch e {
	case ImageObjectImage:
		return true
	default:
		return false
	}
}

// Defines values for ImageListObject.
const (
	ImageListObjectList ImageListObject = "list"
)

// Valid indicates whether the value is a known member of the ImageListObject enum.
func (e ImageListObject) Valid() bool {
	switch e {
	case ImageListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for ListEnvelopeObject.
const (
	ListEnvelopeObjectList ListEnvelopeObject = "list"
)

// Valid indicates whether the value is a known member of the ListEnvelopeObject enum.
func (e ListEnvelopeObject) Valid() bool {
	switch e {
	case ListEnvelopeObjectList:
		return true
	default:
		return false
	}
}

// Defines values for QueueObject.
const (
	QueueObjectQueue QueueObject = "queue"
)

// Valid indicates whether the value is a known member of the QueueObject enum.
func (e QueueObject) Valid() bool {
	switch e {
	case QueueObjectQueue:
		return true
	default:
		return false
	}
}

// Defines values for SandboxObject.
const (
	SandboxObjectSandbox SandboxObject = "sandbox"
)

// Valid indicates whether the value is a known member of the SandboxObject enum.
func (e SandboxObject) Valid() bool {
	switch e {
	case SandboxObjectSandbox:
		return true
	default:
		return false
	}
}

// Defines values for SandboxListObject.
const (
	SandboxListObjectList SandboxListObject = "list"
)

// Valid indicates whether the value is a known member of the SandboxListObject enum.
func (e SandboxListObject) Valid() bool {
	switch e {
	case SandboxListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for SandboxSourceType.
const (
	SandboxSourceTypeGit     SandboxSourceType = "git"
	SandboxSourceTypeTarball SandboxSourceType = "tarball"
)

// Valid indicates whether the value is a known member of the SandboxSourceType enum.
func (e SandboxSourceType) Valid() bool {
	switch e {
	case SandboxSourceTypeGit:
		return true
	case SandboxSourceTypeTarball:
		return true
	default:
		return false
	}
}

// Defines values for SandboxSourceParamsType.
const (
	SandboxSourceParamsTypeGit     SandboxSourceParamsType = "git"
	SandboxSourceParamsTypeTarball SandboxSourceParamsType = "tarball"
)

// Valid indicates whether the value is a known member of the SandboxSourceParamsType enum.
func (e SandboxSourceParamsType) Valid() bool {
	switch e {
	case SandboxSourceParamsTypeGit:
		return true
	case SandboxSourceParamsTypeTarball:
		return true
	default:
		return false
	}
}

// Defines values for SandboxState.
const (
	SandboxStateRunning   SandboxState = "running"
	SandboxStateStopped   SandboxState = "stopped"
	SandboxStateSuspended SandboxState = "suspended"
)

// Valid indicates whether the value is a known member of the SandboxState enum.
func (e SandboxState) Valid() bool {
	switch e {
	case SandboxStateRunning:
		return true
	case SandboxStateStopped:
		return true
	case SandboxStateSuspended:
		return true
	default:
		return false
	}
}

// Defines values for SandboxStopReason.
const (
	SandboxStopReasonExpired   SandboxStopReason = "expired"
	SandboxStopReasonFailed    SandboxStopReason = "failed"
	SandboxStopReasonIdle      SandboxStopReason = "idle"
	SandboxStopReasonStopped   SandboxStopReason = "stopped"
	SandboxStopReasonSuspended SandboxStopReason = "suspended"
)

// Valid indicates whether the value is a known member of the SandboxStopReason enum.
func (e SandboxStopReason) Valid() bool {
	switch e {
	case SandboxStopReasonExpired:
		return true
	case SandboxStopReasonFailed:
		return true
	case SandboxStopReasonIdle:
		return true
	case SandboxStopReasonStopped:
		return true
	case SandboxStopReasonSuspended:
		return true
	default:
		return false
	}
}

// Defines values for TaskObject.
const (
	TaskObjectTask TaskObject = "task"
)

// Valid indicates whether the value is a known member of the TaskObject enum.
func (e TaskObject) Valid() bool {
	switch e {
	case TaskObjectTask:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusDone    TaskStatus = "done"
	TaskStatusFailed  TaskStatus = "failed"
	TaskStatusPending TaskStatus = "pending"
	TaskStatusRunning TaskStatus = "running"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusDone:
		return true
	case TaskStatusFailed:
		return true
	case TaskStatusPending:
		return true
	case TaskStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for TenantObject.
const (
	TenantObjectTenant TenantObject = "tenant"
)

// Valid indicates whether the value is a known member of the TenantObject enum.
func (e TenantObject) Valid() bool {
	switch e {
	case TenantObjectTenant:
		return true
	default:
		return false
	}
}

// Defines values for TenantFullPolicy.
const (
	Evict    TenantFullPolicy = "evict"
	Preserve TenantFullPolicy = "preserve"
)

// Valid indicates whether the value is a known member of the TenantFullPolicy enum.
func (e TenantFullPolicy) Valid() bool {
	switch e {
	case Evict:
		return true
	case Preserve:
		return true
	default:
		return false
	}
}

// Defines values for TenantListObject.
const (
	TenantListObjectList TenantListObject = "list"
)

// Valid indicates whether the value is a known member of the TenantListObject enum.
func (e TenantListObject) Valid() bool {
	switch e {
	case TenantListObjectList:
		return true
	default:
		return false
	}
}

// Directory A directory in the sandbox. Deliberately not a `File`: a directory has no
// bytes, and a `size_bytes: 0` on one would be a number a caller could
// believe.
type Directory struct {
	Object DirectoryObject `json:"object"`
	Path   string          `json:"path"`
}

// DirectoryObject defines model for Directory.Object.
type DirectoryObject string

// DirectoryCreateParams defines model for DirectoryCreateParams.
type DirectoryCreateParams struct {
	// Path Absolute path inside the sandbox. Parents are created. Validated
	// before it reaches the guest: a relative path, or one containing `..`,
	// is refused rather than resolved into whatever it would have meant.
	Path string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	// Code A stable, machine-readable identifier. Switch on this. The message is
	// for humans and may be reworded at any time.
	Code string `json:"code"`

	// Message A human-readable explanation. Never parse it.
	Message string `json:"message"`

	// Param Which request field was at fault, when one was.
	Param *string `json:"param,omitempty"`

	// RequestId Quote this when reporting a problem.
	RequestId *string `json:"request_id,omitempty"`

	// Type The class of error, which determines what a client should *do*:
	//
	// - `invalid_request_error` — the request is wrong. Retrying it unchanged
	//   will fail identically.
	// - `authentication_error` — the token is missing or wrong.
	// - `capacity_error` — no room right now. Retrying later may work; a task
	//   would not have failed at all.
	// - `idempotency_error` — an Idempotency-Key was reused with a different
	//   body.
	// - `api_error` — our fault. Safe to retry with the same Idempotency-Key.
	Type ErrorType `json:"type"`
}

// ErrorEnvelope The body of every non-2xx reply.
type ErrorEnvelope struct {
	Error Error `json:"error"`
}

// ErrorType The class of error, which determines what a client should *do*:
//
//   - `invalid_request_error` — the request is wrong. Retrying it unchanged
//     will fail identically.
//   - `authentication_error` — the token is missing or wrong.
//   - `capacity_error` — no room right now. Retrying later may work; a task
//     would not have failed at all.
//   - `idempotency_error` — an Idempotency-Key was reused with a different
//     body.
//   - `api_error` — our fault. Safe to retry with the same Idempotency-Key.
type ErrorType string

// Execution defines model for Execution.
type Execution struct {
	Args       *[]string `json:"args,omitempty"`
	Cmd        string    `json:"cmd"`
	Created    time.Time `json:"created"`
	DurationMs *int      `json:"duration_ms,omitempty"`

	// Error Why the command could never start. Set only when status is `failed`.
	Error    *string         `json:"error,omitempty"`
	ExitCode *int            `json:"exit_code,omitempty"`
	Finished *time.Time      `json:"finished,omitempty"`
	Id       string          `json:"id"`
	Object   ExecutionObject `json:"object"`
	Sandbox  string          `json:"sandbox"`

	// Signal The signal that killed it, if one did.
	Signal *string `json:"signal,omitempty"`

	// Status Outcomes that all look like failure but are not, and a caller must tell
	// apart:
	//
	// - `running` — still going.
	// - `exited` — your code ran to completion. `exit_code` is its own verdict.
	// - `timed_out` — it exceeded its timeout and we killed it.
	// - `canceled` — you cancelled it.
	// - `vanished` — **we took the VM away.** Your code did not fail.
	// - `failed` — the command could never start, e.g. no such binary.
	Status          ExecutionStatus `json:"status"`
	Stderr          string          `json:"stderr"`
	StderrTruncated *bool           `json:"stderr_truncated,omitempty"`
	Stdout          string          `json:"stdout"`

	// StdoutTruncated Output exceeded the retention cap and the oldest bytes were dropped.
	// The *tail* is kept, because that is where a traceback is. Never
	// silently truncated: a partial log that looks complete is worse than
	// no log.
	StdoutTruncated *bool `json:"stdout_truncated,omitempty"`
}

// ExecutionObject defines model for Execution.Object.
type ExecutionObject string

// ExecutionCancelParams defines model for ExecutionCancelParams.
type ExecutionCancelParams struct {
	// Signal The signal to send. It reaches the whole process group.
	Signal *string `json:"signal,omitempty"`
}

// ExecutionCreateParams defines model for ExecutionCreateParams.
type ExecutionCreateParams struct {
	Args *[]string `json:"args,omitempty"`
	Cmd  string    `json:"cmd"`

	// Cols Initial terminal width in columns, for a `tty` execution. Defaults to
	// 80 when omitted; ignored without `tty`.
	Cols *int    `json:"cols,omitempty"`
	Cwd  *string `json:"cwd,omitempty"`

	// Env Merged over the sandbox's env; these win. Write-only.
	Env *map[string]string `json:"env,omitempty"`

	// Rows Initial terminal height in rows, for a `tty` execution. Defaults to
	// 24 when omitted; ignored without `tty`.
	Rows *int `json:"rows,omitempty"`

	// Stdin Written to the process, then closed.
	Stdin *[]byte `json:"stdin,omitempty"`

	// TimeoutSeconds Kills the process group when exceeded.
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`

	// Tty Run the command against a pseudo-terminal instead of pipes. The
	// process sees an interactive terminal, so line editing, colour and
	// programs that refuse to run without one all work.
	//
	// stdout and stderr are merged — a terminal has one output stream — so
	// everything arrives on `stdout`. Resize the window with the resize
	// route, and stream input through the stdin route as keystrokes.
	Tty *bool `json:"tty,omitempty"`
}

// ExecutionList defines model for ExecutionList.
type ExecutionList struct {
	Data []Execution `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool                `json:"has_more"`
	Object  ExecutionListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// ExecutionListObject defines model for ExecutionList.Object.
type ExecutionListObject string

// ExecutionResizeParams defines model for ExecutionResizeParams.
type ExecutionResizeParams struct {
	// Cols The new terminal width, in columns.
	Cols int `json:"cols"`

	// Rows The new terminal height, in rows.
	Rows int `json:"rows"`
}

// ExecutionStatus Outcomes that all look like failure but are not, and a caller must tell
// apart:
//
// - `running` — still going.
// - `exited` — your code ran to completion. `exit_code` is its own verdict.
// - `timed_out` — it exceeded its timeout and we killed it.
// - `canceled` — you cancelled it.
// - `vanished` — **we took the VM away.** Your code did not fail.
// - `failed` — the command could never start, e.g. no such binary.
type ExecutionStatus string

// File defines model for File.
type File struct {
	// Mode The permission bits the file ended up with, octal. Set explicitly
	// rather than left to whatever umask the guest happens to have, so this
	// is what was asked for and not an approximation of it.
	Mode      *string    `json:"mode,omitempty"`
	Object    FileObject `json:"object"`
	Path      string     `json:"path"`
	SizeBytes int        `json:"size_bytes"`
}

// FileObject defines model for File.Object.
type FileObject string

// FileBatchCreateParams defines model for FileBatchCreateParams.
type FileBatchCreateParams struct {
	// Files The files to write, in the order they will be written. An entry is
	// exactly a single-file upload, so a path or mode this route refuses is
	// one the single-file route refuses too -- there is one set of rules,
	// not two.
	Files []FileCreateParams `json:"files"`
}

// FileCreateParams defines model for FileCreateParams.
type FileCreateParams struct {
	// Content The file's bytes, base64 encoded so binary survives the trip.
	Content []byte `json:"content"`

	// Mode Permission bits, octal -- `0755` for something you intend to execute.
	// Defaults to `0644`, so an upload is readable and not runnable unless
	// you say otherwise.
	//
	// Three digits, with an optional leading zero. setuid, setgid and the
	// sticky bit are refused with an `invalid_request_error` on `mode`: the
	// host writes this file as root, and the one thing an upload must never
	// be able to do is leave a root-owned setuid binary behind for whatever
	// runs in the guest next. Code inside the sandbox can still chmod its
	// own files -- then it is the guest's own doing, and stays inside the
	// guest.
	Mode *string `json:"mode,omitempty"`

	// Path Absolute path inside the sandbox. Parent directories are created.
	Path string `json:"path"`
}

// FileList defines model for FileList.
type FileList struct {
	Data []File `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool           `json:"has_more"`
	Object  FileListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// FileListObject defines model for FileList.Object.
type FileListObject string

// Frame One event in an execution's stream, sent as an SSE data payload.
type Frame struct {
	// Data The chunk, base64 so binary output survives the trip.
	Data     *[]byte     `json:"data,omitempty"`
	ExitCode *int        `json:"exit_code,omitempty"`
	Message  *string     `json:"message,omitempty"`
	Object   FrameObject `json:"object"`
	Pid      *int        `json:"pid,omitempty"`
	Signal   *string     `json:"signal,omitempty"`
	TimedOut *bool       `json:"timed_out,omitempty"`
	Type     FrameType   `json:"type"`
}

// FrameObject defines model for Frame.Object.
type FrameObject string

// FrameType defines model for Frame.Type.
type FrameType string

// Health defines model for Health.
type Health struct {
	Object  HealthObject `json:"object"`
	Ok      bool         `json:"ok"`
	Version string       `json:"version"`
}

// HealthObject defines model for Health.Object.
type HealthObject string

// Image defines model for Image.
type Image struct {
	Arch      *string     `json:"arch,omitempty"`
	Id        string      `json:"id"`
	Language  string      `json:"language"`
	Object    ImageObject `json:"object"`
	SizeBytes *int        `json:"size_bytes,omitempty"`
}

// ImageObject defines model for Image.Object.
type ImageObject string

// ImageList defines model for ImageList.
type ImageList struct {
	Data []Image `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool            `json:"has_more"`
	Object  ImageListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// ImageListObject defines model for ImageList.Object.
type ImageListObject string

// ListEnvelope defines model for ListEnvelope.
type ListEnvelope struct {
	Data []map[string]interface{} `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool               `json:"has_more"`
	Object  ListEnvelopeObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// ListEnvelopeObject defines model for ListEnvelope.Object.
type ListEnvelopeObject string

// Queue defines model for Queue.
type Queue struct {
	// Busy This node's slots currently running something.
	Busy   int `json:"busy"`
	Done   int `json:"done"`
	Failed int `json:"failed"`

	// Leased Held by a worker somewhere in the fleet.
	Leased int         `json:"leased"`
	Object QueueObject `json:"object"`

	// OldestPendingMs How long the head of the queue has waited. This is the number that
	// says whether the fleet is big enough.
	OldestPendingMs int `json:"oldest_pending_ms"`
	Pending         int `json:"pending"`

	// Slots This node's slots. Not the fleet's.
	Slots int `json:"slots"`
}

// QueueObject defines model for Queue.Object.
type QueueObject string

// Sandbox defines model for Sandbox.
type Sandbox struct {
	Created time.Time `json:"created"`

	// Expires When the TTL kills it, whatever it is doing. Movable with
	// `POST /sandboxes/{sandbox}/extend`, but only up to the host's maximum
	// lifetime counted from `created`, so this field can be pushed back and
	// never removed.
	Expires time.Time `json:"expires"`
	Id      string    `json:"id"`
	Image   string    `json:"image"`
	MemMib  *int      `json:"mem_mib,omitempty"`

	// Name The handle this sandbox was created with, if any. It is unique among
	// your running sandboxes and is what `get_or_create` resolves, so you
	// can address "the sandbox called build" without storing its id.
	//
	// It frees the moment the sandbox stops: create the next `build` and it
	// is a fresh VM. Absent when the sandbox was created without one.
	Name *string `json:"name,omitempty"`

	// Network Whether filtered egress is on.
	Network *bool         `json:"network,omitempty"`
	Object  SandboxObject `json:"object"`

	// Source What this sandbox was seeded from, when it was seeded at all. Absent
	// otherwise -- a sandbox with no `source` has no empty source object.
	//
	// Never the URL as it was sent. See `url_redacted`.
	Source *SandboxSource `json:"source,omitempty"`

	// State - `running` — has a live VM.
	// - `stopped` — gone for good; kept only briefly for its final metering.
	// - `suspended` — snapshotted to disk and torn down, resumable under the
	//   same id with `POST /sandboxes/{sandbox}/resume`. Costs no CPU or memory,
	//   only the snapshot, and keeps its slot and name so a resume cannot be
	//   refused for either.
	State SandboxState `json:"state"`

	// Stats What a sandbox has consumed. Cumulative since boot, so a biller must
	// diff two samples: booting alone costs a couple of CPU-seconds, and
	// cumulative idle is meaningless for a sandbox's first seconds.
	Stats Stats `json:"stats"`

	// StopReason Set once the sandbox is stopped.
	StopReason *SandboxStopReason `json:"stop_reason,omitempty"`
	Stopped    *time.Time         `json:"stopped,omitempty"`

	// Storage Where this sandbox's files persist, when the node has object storage
	// configured. Absent when it does not.
	Storage *SandboxStorage `json:"storage,omitempty"`

	// Tags The labels set at create time, returned exactly as they were given.
	//
	// Unlike `env`, tags **are** returned -- here, and in every list that
	// includes this sandbox. Never put a credential in one. A secret that
	// needs to reach the guest is what `env` is for, and `env` is
	// write-only precisely so this mistake cannot be made by accident.
	Tags  *map[string]string `json:"tags,omitempty"`
	Vcpus *int               `json:"vcpus,omitempty"`
}

// SandboxObject defines model for Sandbox.Object.
type SandboxObject string

// SandboxCreateParams defines model for SandboxCreateParams.
type SandboxCreateParams struct {
	// CpuCores A hard CPU ceiling; may be fractional. 0.5 means half a core, enforced.
	CpuCores *float64 `json:"cpu_cores,omitempty"`
	DiskBps  *int     `json:"disk_bps,omitempty"`
	DiskIops *int     `json:"disk_iops,omitempty"`
	DiskMib  *int     `json:"disk_mib,omitempty"`

	// Env Injected into every execution in this sandbox. An execution's own
	// env wins where they overlap.
	//
	// Write-only. These usually carry credentials, so they are never
	// logged and no endpoint returns them. They are applied by the host on
	// each execution rather than written into the guest's filesystem,
	// where anything inside could read them long after the command that
	// needed them.
	Env *map[string]string `json:"env,omitempty"`

	// GetOrCreate When `name` already belongs to one of your running sandboxes, return
	// that sandbox instead of creating one — a 200 with the existing
	// sandbox rather than a 201 with a new one. Without it, a duplicate
	// `name` is refused with a 409.
	//
	// The existing sandbox is returned as it is: the other fields here are
	// the shape a create *would* have used and are ignored when there is
	// nothing to create. Requires `name`.
	GetOrCreate *bool `json:"get_or_create,omitempty"`

	// IdleSeconds Reclaim after this long with nothing running. Negative disables it.
	IdleSeconds *int `json:"idle_seconds,omitempty"`

	// Image The language image.
	Image  string `json:"image"`
	MemMib *int   `json:"mem_mib,omitempty"`

	// Name A stable handle for this sandbox, unique among your running
	// sandboxes. Letters, digits and `_-.`, at most 64 bytes.
	//
	// On its own it just labels the sandbox and makes a duplicate name a
	// 409. With `get_or_create` it becomes a lookup: the same name returns
	// the sandbox you already have rather than booting a second one, so a
	// stable identity outlives any single request without you storing an id.
	//
	// Scoped to your API key, so two tenants may both have a `build` and
	// neither can name the other's. It frees when the sandbox stops.
	Name *string `json:"name,omitempty"`

	// Network Filtered egress. The public internet is reachable; every private
	// range, link-local and the cloud metadata endpoint are not.
	Network *bool `json:"network,omitempty"`

	// NetworkBps Caps bandwidth both ways, in bytes per second. Worth setting even
	// when CPU is capped: a sandbox pinned to a quarter core can still
	// saturate the host's uplink, and the first you hear of it is the
	// abuse complaint.
	NetworkBps *int `json:"network_bps,omitempty"`

	// Source A project to seed the sandbox with, fetched by the daemon before this
	// create returns. Without it, getting a project in is one request per
	// file, or a clone inside the guest -- which needs `network: true`, is
	// impossible for a network-isolated sandbox, and puts your credential
	// inside a VM that is untrusted by design.
	//
	// Off unless the operator enabled it. See `SandboxSourceParams`.
	Source *SandboxSourceParams `json:"source,omitempty"`

	// Storage Options for this sandbox's storage mount. The namespace is never set
	// here — it comes from your API key. Only the read/write posture is
	// yours to choose, and only to tighten.
	Storage *SandboxStorageParams `json:"storage,omitempty"`

	// Tags Labels of your own, for finding this sandbox again: filter
	// `GET /sandboxes` by `tag`, or read them back off the object.
	//
	// At most 10 pairs, keys at most 64 bytes and values at most 256. Bytes
	// rather than characters, so a key written in emoji runs out about four
	// times sooner than its length suggests. A key may not be empty and may
	// not contain `:`, which is the character the `tag` filter splits on.
	//
	// Node-local, like the list they are filtered on: they live in the
	// daemon's memory beside the sandbox and go when it is forgotten. They
	// are not written into the guest and nothing inside it can read them,
	// which is what separates them from `env` -- a tag names a sandbox, it
	// does not configure one.
	//
	// **Returned by the API, unlike `env`.** Anything that can read this
	// sandbox can read its tags -- which is its own tenant, and an admin key
	// -- so a tag is a label and never a secret.
	Tags *map[string]string `json:"tags,omitempty"`

	// TtlSeconds Maximum lifetime. The sandbox is killed when it elapses. Capped by
	// the host's own maximum, and extensible later within that cap with
	// `POST /sandboxes/{sandbox}/extend`.
	//
	// It is time to run things in, so seeding a `source` does not consume it:
	// the clock starts once the project is in the guest. A `ttl_seconds`
	// shorter than the seed takes is refused naming this field.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
	Vcpus      *int `json:"vcpus,omitempty"`
}

// SandboxExtendParams defines model for SandboxExtendParams.
type SandboxExtendParams struct {
	// TtlSeconds How much longer the sandbox should live, counted from now rather than
	// from its current deadline -- a heartbeat says "give me ten more
	// minutes", and repeating it does not stack.
	//
	// What you get is the later of the existing deadline and this one. More
	// than the host's maximum lifetime from creation still has left is
	// refused, not trimmed. The reply's `expires` is the answer; this number
	// is a request.
	TtlSeconds int `json:"ttl_seconds"`
}

// SandboxList defines model for SandboxList.
type SandboxList struct {
	Data []Sandbox `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool              `json:"has_more"`
	Object  SandboxListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// SandboxListObject defines model for SandboxList.Object.
type SandboxListObject string

// SandboxSource Where a sandbox was seeded from. Reported so that a sandbox found later can
// be traced back to the code in it, which is otherwise unknowable from
// outside the guest.
type SandboxSource struct {
	// Commit The commit that was actually checked out, resolved. A branch names a
	// moving target and a tag can be moved under you; this is the only field
	// here that says the same thing tomorrow. Absent for a tarball.
	Commit *string `json:"commit,omitempty"`

	// CredentialRef The operator credential that was used, by name. Safe to return because
	// it was never the secret -- it is the name of one.
	CredentialRef *string `json:"credential_ref,omitempty"`

	// Ref The git ref that was asked for. Absent for a tarball.
	Ref  *string           `json:"ref,omitempty"`
	Type SandboxSourceType `json:"type"`

	// UrlRedacted The scheme, host and path of what was fetched. Userinfo, query and
	// fragment are cut off, and the field says so in its name so that nobody
	// passes it to a fetcher expecting it to work.
	//
	// Cut down because a URL is routinely a credential: a presigned object
	// URL carries its signature in the query, and `https://user:token@host/`
	// carries a token in plain sight. Tags taught this -- everything the API
	// returns is readable by the tenant and by an admin key, so nothing the
	// API returns may be a secret. A URL is the first field where that rule
	// is not obvious, which is exactly why it is applied here.
	UrlRedacted string `json:"url_redacted"`
}

// SandboxSourceType defines model for SandboxSource.Type.
type SandboxSourceType string

// SandboxSourceParams Where to get the project this sandbox starts with.
//
// The daemon fetches it, expands it host-side, and writes the result into the
// guest's working directory over the same endpoints a file upload uses. It is
// done before the create returns and it counts as activity, so a slow seed
// cannot be reclaimed as idle halfway through.
//
// **Off unless the operator turned it on.** Fetching needs `-source-fetch`,
// and every host that may be fetched from must be named with
// `-source-allow-host`; either one missing refuses every `source` with
// `source_not_permitted`. An empty allowlist fetches nothing, so enabling the
// flag alone changes nothing. The gate is the point rather than paperwork:
// the daemon sits outside the firewall it installs for guests, so a URL it
// will fetch on request is a URL an operator has to have agreed to.
//
// Bounded by the operator too, with `-source-max-bytes` on what is
// downloaded, `-source-max-expanded-bytes` on what is written, and
// `-source-max-files` on how many members an archive may hold. Past any of
// them is `source_fetch_failed`.
//
// There is deliberately no destination field. The project lands in the
// guest's working directory -- where a relative path in a file upload lands --
// and a caller-chosen root would only be a way to write over the image's own
// `/usr` and `/etc` before anything in the sandbox runs.
type SandboxSourceParams struct {
	// CredentialRef The **name** of a credential the operator configured with
	// `-source-credential`, for a private repository. Git only.
	//
	// Not the credential. A secret in a request body is a secret in an access
	// log, in a proxy, and in whatever retried the request -- the same
	// reasoning that made the storage namespace derive from your key instead
	// of arriving in the body. A name the operator did not configure is
	// `source_not_permitted`, like an unreachable URL, and for the same
	// reason: the difference is the operator's business, not the caller's.
	//
	// The secret it names never enters the URL and never enters the guest. The
	// clone happens on the host and only the working tree is copied in, so
	// nothing in the sandbox can read the token that fetched it -- which is
	// the whole reason this is not a clone inside the guest.
	CredentialRef *string `json:"credential_ref,omitempty"`

	// Depth How much history to fetch, in commits. Git only.
	//
	// Defaults to 1, because the sandbox needs a working tree and the commits
	// behind it are bytes nothing in there will read. Raise it only when
	// something you intend to run walks the history. The `.git` directory is
	// not written into the guest either way.
	Depth *int `json:"depth,omitempty"`

	// Ref Branch, tag or full commit SHA to check out. Git only. Defaults to the
	// remote's default branch.
	//
	// Prefer a SHA. It is the only one of the three that resolves to the same
	// code twice, and the sandbox reports back the commit it actually got.
	Ref *string `json:"ref,omitempty"`

	// StripComponents Leading path elements to drop from every member, like `tar
	// --strip-components`. Tarball only.
	//
	// `1` is the usual value: a release tarball wraps everything in a single
	// directory named after the version, and without this the project arrives
	// one level deeper than every path inside it expects.
	//
	// A member with fewer elements than this is skipped rather than refused --
	// a `LICENSE` sitting beside the wrapper directory is normal. An archive
	// where every member is skipped is `source_fetch_failed`, because a
	// sandbox seeded with nothing is not what was asked for and an empty
	// working directory is the hardest kind of failure to debug later.
	StripComponents *int `json:"strip_components,omitempty"`

	// Type Which fetcher to use.
	//
	// The remaining fields are per-type: `strip_components` belongs to a
	// tarball, and `ref`, `depth` and `credential_ref` to a git clone. One
	// sent with the wrong type is an `invalid_request_error` naming the field,
	// not a field quietly dropped -- a caller who set `ref` on a tarball meant
	// something by it, and seeding the default branch instead would be the
	// wrong project delivered silently.
	Type SandboxSourceParamsType `json:"type"`

	// Url What to fetch.
	//
	// `https` only. An `http` seed is a project any network attacker on the
	// path gets to rewrite before it runs, and `file://`, `ftp://`,
	// `gopher://` and git's own `ext::` -- which is a command, not a
	// transport -- are refused by the same check. They name things on the
	// host, and the host is the one place this URL must never reach.
	//
	// The host must be on the operator's `-source-allow-host` list, and so
	// must every redirect hop: an allowlist checked once is an allowlist a
	// 302 walks around. Where the name resolves is re-checked at connect
	// time on every hop, against the private, loopback, link-local and
	// IPv4-mapped ranges the guest firewall already blocks -- so a name that
	// resolves to `169.254.169.254`, or rebinds to it between the check and
	// the connect, does not get a socket.
	//
	// Every one of those refusals is the same `source_not_permitted` with the
	// same message. Distinguishing them would turn this field into a port
	// scanner that reads the host's routing table.
	//
	// No credential in here. `credential_ref` is where one goes, and this
	// value comes back on the sandbox with its userinfo and query removed
	// precisely because callers put them here anyway.
	Url string `json:"url"`
}

// SandboxSourceParamsType Which fetcher to use.
//
// The remaining fields are per-type: `strip_components` belongs to a
// tarball, and `ref`, `depth` and `credential_ref` to a git clone. One
// sent with the wrong type is an `invalid_request_error` naming the field,
// not a field quietly dropped -- a caller who set `ref` on a tarball meant
// something by it, and seeding the default branch instead would be the
// wrong project delivered silently.
type SandboxSourceParamsType string

// SandboxState - `running` — has a live VM.
//   - `stopped` — gone for good; kept only briefly for its final metering.
//   - `suspended` — snapshotted to disk and torn down, resumable under the
//     same id with `POST /sandboxes/{sandbox}/resume`. Costs no CPU or memory,
//     only the snapshot, and keeps its slot and name so a resume cannot be
//     refused for either.
type SandboxState string

// SandboxStopReason Why a sandbox has no running VM. `stopped` means you asked; `suspended`
// means it was snapshotted for later; the rest happened to it, and only
// `failed` means something went wrong.
type SandboxStopReason string

// SandboxStorage A sandbox's view of object storage. Files written here outlive the
// sandbox and are reachable by every sandbox in the same `namespace`, which
// is how state is carried from one run to the next.
type SandboxStorage struct {
	// MaxBytes Your tenant's total storage cap in bytes, or 0 for unlimited. This is
	// the limit your writes are measured against; it is set by an admin.
	MaxBytes *int64 `json:"max_bytes,omitempty"`

	// MountPath Where storage is mounted inside the guest, e.g. `/mnt/storage`. This
	// is a directory in your own sandbox, not a namespace, so choosing it
	// reaches nobody else's files. Defaults to `/mnt/storage`.
	MountPath *string `json:"mount_path,omitempty"`

	// Namespace The tenant your files live under, derived from your API key. It is
	// yours and stable: write a file today, read it from another sandbox
	// tomorrow. You cannot choose it — that is what stops one tenant from
	// naming another's.
	Namespace string `json:"namespace"`

	// Policy What a write does when the cap is reached. Absent when there is no cap.
	Policy *TenantFullPolicy `json:"policy,omitempty"`

	// ReadOnly Whether this sandbox may write, or only read.
	ReadOnly bool `json:"read_only"`
}

// SandboxStorageParams What a create request may say about storage, which is very little.
type SandboxStorageParams struct {
	// MountPath Where to mount storage inside the guest. An absolute, clean path using
	// only letters, digits and `_-./`; it names a directory in your own
	// sandbox and cannot reach another tenant's files. Defaults to
	// `/mnt/storage`.
	MountPath *string `json:"mount_path,omitempty"`

	// ReadOnly Mount storage read-only for this sandbox even if the key could write.
	// It can only tighten: a read-only key stays read-only whatever you set
	// here. Useful for a run that should read shared state but never touch it.
	ReadOnly *bool `json:"read_only,omitempty"`
}

// Stats What a sandbox has consumed. Cumulative since boot, so a biller must
// diff two samples: booting alone costs a couple of CPU-seconds, and
// cumulative idle is meaningless for a sandbox's first seconds.
type Stats struct {
	// ActiveCpuMs CPU actually burned. **This is the billable number.** A sandbox
	// blocked on I/O bills nearly nothing: three seconds asleep costs
	// about 15ms of this.
	ActiveCpuMs int `json:"active_cpu_ms"`

	// IdleMs `wall_ms` minus `active_cpu_ms`: existing but doing nothing. Zero
	// when a multi-vCPU sandbox burns more CPU than wall-clock.
	IdleMs             int `json:"idle_ms"`
	MemoryCurrentBytes int `json:"memory_current_bytes"`

	// MemoryPeakBytes The high-water mark, which is what a memory limit must be sized against.
	MemoryPeakBytes int `json:"memory_peak_bytes"`

	// NetworkRxBytes Bytes the guest received.
	//
	// Read from the host's TAP device, where the direction necessarily
	// inverts: what the guest sends is what the host receives. Both network
	// fields are named from the **guest's** point of view, so `rx` is what
	// came into the sandbox and `tx` is what it sent out. Do not line them
	// up with host-side counters of the same name -- those are the other way
	// round, and the mistake is invisible until an egress bill or an abuse
	// report says otherwise.
	//
	// Absent when the sandbox has no network device: with `network: false`
	// there is no TAP, and "nothing to count" is not the same claim as
	// zero bytes.
	NetworkRxBytes *int64 `json:"network_rx_bytes,omitempty"`

	// NetworkTxBytes Bytes the guest sent. This is the egress number -- the one a bandwidth
	// cap limits and an abuse complaint is about. Counted at the host's TAP
	// and named from the guest's side, like `network_rx_bytes`.
	NetworkTxBytes *int64 `json:"network_tx_bytes,omitempty"`

	// WallMs How long the sandbox has existed.
	WallMs int `json:"wall_ms"`
}

// Task defines model for Task.
type Task struct {
	ActiveCpuMs *int `json:"active_cpu_ms,omitempty"`

	// Attempts How many tries it took. Retries are for nodes dying, not for code
	// failing: a task whose process exits non-zero is never retried, or a
	// caller's bug would be run repeatedly and billed for each attempt.
	Attempts *int       `json:"attempts,omitempty"`
	Created  *time.Time `json:"created,omitempty"`

	// Error An infrastructure failure. Distinct from a non-zero exit, which is
	// the caller's own code and not a failure of ours.
	Error           *string    `json:"error,omitempty"`
	ExitCode        *int       `json:"exit_code,omitempty"`
	Finished        *time.Time `json:"finished,omitempty"`
	Id              string     `json:"id"`
	MemoryPeakBytes *int       `json:"memory_peak_bytes,omitempty"`
	Object          TaskObject `json:"object"`
	Started         *time.Time `json:"started,omitempty"`

	// Status - `pending` — waiting for a slot anywhere in the fleet.
	// - `running` — a node holds it.
	// - `done` — it ran. `exit_code` is your code's own verdict, and a
	//   non-zero one is still `done`.
	// - `failed` — **our** failure: no node could run it, after its attempts
	//   ran out.
	Status TaskStatus `json:"status"`
	Stderr *string    `json:"stderr,omitempty"`
	Stdout *string    `json:"stdout,omitempty"`
}

// TaskObject defines model for Task.Object.
type TaskObject string

// TaskCreateParams defines model for TaskCreateParams.
type TaskCreateParams struct {
	Args     *[]string `json:"args,omitempty"`
	Cmd      string    `json:"cmd"`
	CpuCores *float64  `json:"cpu_cores,omitempty"`

	// Env Write-only.
	Env *map[string]string `json:"env,omitempty"`

	// Files Written into the sandbox before the command runs, keyed by path.
	Files *map[string][]byte `json:"files,omitempty"`
	Image string             `json:"image"`

	// MaxAttempts How many times a node may try this before it is failed for good. Two
	// means one retry: enough to survive a node dying, few enough that a
	// task which reliably kills its worker cannot cycle the fleet forever.
	MaxAttempts *int  `json:"max_attempts,omitempty"`
	MemMib      *int  `json:"mem_mib,omitempty"`
	Network     *bool `json:"network,omitempty"`

	// Priority Scheduling priority, 0 to 10. Higher runs first; equal priorities are
	// FIFO, which is the guarantee callers actually reason about. It orders
	// the queue within what a node can fit: among the tasks a node has room
	// for, the highest priority is taken first, so a high-priority task that
	// does not fit yields to a lower one that does rather than blocking it.
	Priority       *int `json:"priority,omitempty"`
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`
	Vcpus          *int `json:"vcpus,omitempty"`
}

// TaskStatus - `pending` — waiting for a slot anywhere in the fleet.
//   - `running` — a node holds it.
//   - `done` — it ran. `exit_code` is your code's own verdict, and a
//     non-zero one is still `done`.
//   - `failed` — **our** failure: no node could run it, after its attempts
//     ran out.
type TaskStatus string

// Tenant defines model for Tenant.
type Tenant struct {
	// Id The tenant namespace this policy applies to.
	Id string `json:"id"`

	// MaxBytes The tenant's total storage cap, in bytes. 0 means unlimited.
	MaxBytes int64        `json:"max_bytes"`
	Object   TenantObject `json:"object"`

	// Policy What a write does when a tenant is at its cap.
	//
	// - `preserve` — reject the write and keep what is stored. For data that
	//   matters more than the next write: an audit trail, a paid-for dataset.
	// - `evict` — delete the oldest objects until the write fits. For a cache
	//   or scratch space, where the newest data is the point. It deletes data,
	//   irreversibly, which is why it is never the default.
	Policy TenantFullPolicy `json:"policy"`

	// UsageBytes Bytes currently stored, read from the object store on retrieve. Absent
	// on the reply to an update, which does not stop to scan the bucket.
	UsageBytes *int64 `json:"usage_bytes,omitempty"`
}

// TenantObject defines model for Tenant.Object.
type TenantObject string

// TenantFullPolicy What a write does when a tenant is at its cap.
//
//   - `preserve` — reject the write and keep what is stored. For data that
//     matters more than the next write: an audit trail, a paid-for dataset.
//   - `evict` — delete the oldest objects until the write fits. For a cache
//     or scratch space, where the newest data is the point. It deletes data,
//     irreversibly, which is why it is never the default.
type TenantFullPolicy string

// TenantList defines model for TenantList.
type TenantList struct {
	Data []Tenant `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool             `json:"has_more"`
	Object  TenantListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// TenantListObject defines model for TenantList.Object.
type TenantListObject string

// TenantUpdateParams defines model for TenantUpdateParams.
type TenantUpdateParams struct {
	// MaxBytes The tenant's total storage cap, in bytes. 0 means unlimited.
	MaxBytes int64 `json:"max_bytes"`

	// Policy What a write does when a tenant is at its cap.
	//
	// - `preserve` — reject the write and keep what is stored. For data that
	//   matters more than the next write: an audit trail, a paid-for dataset.
	// - `evict` — delete the oldest objects until the write fits. For a cache
	//   or scratch space, where the newest data is the point. It deletes data,
	//   irreversibly, which is why it is never the default.
	Policy TenantFullPolicy `json:"policy"`
}

// EndingBefore defines model for EndingBefore.
type EndingBefore = string

// ExecutionId defines model for ExecutionId.
type ExecutionId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// SandboxId defines model for SandboxId.
type SandboxId = string

// StartingAfter defines model for StartingAfter.
type StartingAfter = string

// TaskId defines model for TaskId.
type TaskId = string

// ApiError The body of every non-2xx reply.
type ApiError = ErrorEnvelope

// CapacityExhausted The body of every non-2xx reply.
type CapacityExhausted = ErrorEnvelope

// Conflict The body of every non-2xx reply.
type Conflict = ErrorEnvelope

// Forbidden The body of every non-2xx reply.
type Forbidden = ErrorEnvelope

// InvalidRequest The body of every non-2xx reply.
type InvalidRequest = ErrorEnvelope

// NotFound The body of every non-2xx reply.
type NotFound = ErrorEnvelope

// QueueUnreachable The body of every non-2xx reply.
type QueueUnreachable = ErrorEnvelope

// SourceUnavailable The body of every non-2xx reply.
type SourceUnavailable = ErrorEnvelope

// Unauthorized The body of every non-2xx reply.
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListSandboxesParams defines parameters for ListSandboxes.
type ListSandboxesParams struct {
	// Limit How many objects to return, 1–100.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter A cursor. Returns the page of objects immediately after this ID, which
	// is the ID of the last object on the previous page.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore A cursor, for paging backwards. Returns the page immediately before this
	// ID, which is the ID of the first object on the current page.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// State Only sandboxes in this state.
	State *SandboxState `form:"state,omitempty" json:"state,omitempty"`

	// Tag Only sandboxes carrying this tag, written `key:value`. Repeat the
	// parameter to require several: they AND, so `?tag=env:ci&tag=owner:me`
	// returns the sandboxes carrying both. The split is at the first colon,
	// so a value may contain colons and a key may not.
	//
	// The filter is node-local, because the list is: it searches the
	// sandboxes this node holds, not the fleet's. On more than one node you
	// get this node's answer, and finding a tagged sandbox anywhere means
	// asking each node. A tag nobody set is an empty page, not an error --
	// there is no registry of known keys to be wrong about.
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateSandboxParams defines parameters for CreateSandbox.
type CreateSandboxParams struct {
	// IdempotencyKey Makes a retry safe. A request that never got its reply -- a timeout, a
	// dropped connection -- cannot be known to have failed, so the only sane
	// move is to retry it; without a key, that retry runs the work twice.
	//
	// The first request with a given key is executed and its reply recorded.
	// Any later request with the same key replays that reply, without doing
	// the work again. Keys are held for 24 hours and are scoped to the token.
	//
	// Reusing a key with a *different* request body is an `idempotency_error`:
	// it means the client believes it is retrying something it is not.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	// Limit How many objects to return, 1–100.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter A cursor. Returns the page of objects immediately after this ID, which
	// is the ID of the last object on the previous page.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore A cursor, for paging backwards. Returns the page immediately before this
	// ID, which is the ID of the first object on the current page.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// CreateExecutionParams defines parameters for CreateExecution.
type CreateExecutionParams struct {
	// IdempotencyKey Makes a retry safe. A request that never got its reply -- a timeout, a
	// dropped connection -- cannot be known to have failed, so the only sane
	// move is to retry it; without a key, that retry runs the work twice.
	//
	// The first request with a given key is executed and its reply recorded.
	// Any later request with the same key replays that reply, without doing
	// the work again. Keys are held for 24 hours and are scoped to the token.
	//
	// Reusing a key with a *different* request body is an `idempotency_error`:
	// it means the client believes it is retrying something it is not.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RetrieveFileParams defines parameters for RetrieveFile.
type RetrieveFileParams struct {
	// Path Absolute path inside the sandbox.
	Path string `form:"path" json:"path"`
}

// CreateTaskParams defines parameters for CreateTask.
type CreateTaskParams struct {
	// IdempotencyKey Makes a retry safe. A request that never got its reply -- a timeout, a
	// dropped connection -- cannot be known to have failed, so the only sane
	// move is to retry it; without a key, that retry runs the work twice.
	//
	// The first request with a given key is executed and its reply recorded.
	// Any later request with the same key replays that reply, without doing
	// the work again. Keys are held for 24 hours and are scoped to the token.
	//
	// Reusing a key with a *different* request body is an `idempotency_error`:
	// it means the client believes it is retrying something it is not.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateSandboxJSONRequestBody defines body for CreateSandbox for application/json ContentType.
type CreateSandboxJSONRequestBody = SandboxCreateParams

// CreateDirJSONRequestBody defines body for CreateDir for application/json ContentType.
type CreateDirJSONRequestBody = DirectoryCreateParams

// CreateExecutionJSONRequestBody defines body for CreateExecution for application/json ContentType.
type CreateExecutionJSONRequestBody = ExecutionCreateParams

// CancelExecutionJSONRequestBody defines body for CancelExecution for application/json ContentType.
type CancelExecutionJSONRequestBody = ExecutionCancelParams

// ResizeExecutionJSONRequestBody defines body for ResizeExecution for application/json ContentType.
type ResizeExecutionJSONRequestBody = ExecutionResizeParams

// ExtendSandboxJSONRequestBody defines body for ExtendSandbox for application/json ContentType.
type ExtendSandboxJSONRequestBody = SandboxExtendParams

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = FileCreateParams

// CreateFilesJSONRequestBody defines body for CreateFiles for application/json ContentType.
type CreateFilesJSONRequestBody = FileBatchCreateParams

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskCreateParams

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = TenantUpdateParams
