// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package apitypes

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ErrorType.
const (
	ErrorTypeApiError            ErrorType = "api_error"
	ErrorTypeAuthenticationError ErrorType = "authentication_error"
	ErrorTypeCapacityError       ErrorType = "capacity_error"
	ErrorTypeIdempotencyError    ErrorType = "idempotency_error"
	ErrorTypeInvalidRequestError ErrorType = "invalid_request_error"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ErrorTypeApiError:
		return true
	case ErrorTypeAuthenticationError:
		return true
	case ErrorTypeCapacityError:
		return true
	case ErrorTypeIdempotencyError:
		return true
	case ErrorTypeInvalidRequestError:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionObject.
const (
	ExecutionObjectExecution ExecutionObject = "execution"
)

// Valid indicates whether the value is a known member of the ExecutionObject enum.
func (e ExecutionObject) Valid() bool {
	switch e {
	case ExecutionObjectExecution:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionListObject.
const (
	ExecutionListObjectList ExecutionListObject = "list"
)

// Valid indicates whether the value is a known member of the ExecutionListObject enum.
func (e ExecutionListObject) Valid() bool {
	switch e {
	case ExecutionListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionStatus.
const (
	ExecutionStatusCanceled ExecutionStatus = "canceled"
	ExecutionStatusExited   ExecutionStatus = "exited"
	ExecutionStatusFailed   ExecutionStatus = "failed"
	ExecutionStatusRunning  ExecutionStatus = "running"
	ExecutionStatusTimedOut ExecutionStatus = "timed_out"
	ExecutionStatusVanished ExecutionStatus = "vanished"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case ExecutionStatusCanceled:
		return true
	case ExecutionStatusExited:
		return true
	case ExecutionStatusFailed:
		return true
	case ExecutionStatusRunning:
		return true
	case ExecutionStatusTimedOut:
		return true
	case ExecutionStatusVanished:
		return true
	default:
		return false
	}
}

// Defines values for FileObject.
const (
	FileObjectFile FileObject = "file"
)

// Valid indicates whether the value is a known member of the FileObject enum.
func (e FileObject) Valid() bool {
	switch e {
	case FileObjectFile:
		return true
	default:
		return false
	}
}

// Defines values for FrameObject.
const (
	FrameObjectFrame FrameObject = "frame"
)

// Valid indicates whether the value is a known member of the FrameObject enum.
func (e FrameObject) Valid() bool {
	switch e {
	case FrameObjectFrame:
		return true
	default:
		return false
	}
}

// Defines values for FrameType.
const (
	FrameTypeError   FrameType = "error"
	FrameTypeExit    FrameType = "exit"
	FrameTypeStarted FrameType = "started"
	FrameTypeStderr  FrameType = "stderr"
	FrameTypeStdout  FrameType = "stdout"
)

// Valid indicates whether the value is a known member of the FrameType enum.
func (e FrameType) Valid() bool {
	switch e {
	case FrameTypeError:
		return true
	case FrameTypeExit:
		return true
	case FrameTypeStarted:
		return true
	case FrameTypeStderr:
		return true
	case FrameTypeStdout:
		return true
	default:
		return false
	}
}

// Defines values for HealthObject.
const (
	HealthObjectHealth HealthObject = "health"
)

// Valid indicates whether the value is a known member of the HealthObject enum.
func (e HealthObject) Valid() bool {
	switch e {
	case HealthObjectHealth:
		return true
	default:
		return false
	}
}

// Defines values for ImageObject.
const (
	ImageObjectImage ImageObject = "image"
)

// Valid indicates whether the value is a known member of the ImageObject enum.
func (e ImageObject) Valid() bool {
	switch e {
	case ImageObjectImage:
		return true
	default:
		return false
	}
}

// Defines values for ImageListObject.
const (
	ImageListObjectList ImageListObject = "list"
)

// Valid indicates whether the value is a known member of the ImageListObject enum.
func (e ImageListObject) Valid() bool {
	switch e {
	case ImageListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for ListEnvelopeObject.
const (
	ListEnvelopeObjectList ListEnvelopeObject = "list"
)

// Valid indicates whether the value is a known member of the ListEnvelopeObject enum.
func (e ListEnvelopeObject) Valid() bool {
	switch e {
	case ListEnvelopeObjectList:
		return true
	default:
		return false
	}
}

// Defines values for QueueObject.
const (
	QueueObjectQueue QueueObject = "queue"
)

// Valid indicates whether the value is a known member of the QueueObject enum.
func (e QueueObject) Valid() bool {
	switch e {
	case QueueObjectQueue:
		return true
	default:
		return false
	}
}

// Defines values for SandboxObject.
const (
	SandboxObjectSandbox SandboxObject = "sandbox"
)

// Valid indicates whether the value is a known member of the SandboxObject enum.
func (e SandboxObject) Valid() bool {
	switch e {
	case SandboxObjectSandbox:
		return true
	default:
		return false
	}
}

// Defines values for SandboxListObject.
const (
	SandboxListObjectList SandboxListObject = "list"
)

// Valid indicates whether the value is a known member of the SandboxListObject enum.
func (e SandboxListObject) Valid() bool {
	switch e {
	case SandboxListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for SandboxState.
const (
	SandboxStateRunning SandboxState = "running"
	SandboxStateStopped SandboxState = "stopped"
)

// Valid indicates whether the value is a known member of the SandboxState enum.
func (e SandboxState) Valid() bool {
	switch e {
	case SandboxStateRunning:
		return true
	case SandboxStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for SandboxStopReason.
const (
	SandboxStopReasonExpired SandboxStopReason = "expired"
	SandboxStopReasonFailed  SandboxStopReason = "failed"
	SandboxStopReasonIdle    SandboxStopReason = "idle"
	SandboxStopReasonStopped SandboxStopReason = "stopped"
)

// Valid indicates whether the value is a known member of the SandboxStopReason enum.
func (e SandboxStopReason) Valid() bool {
	switch e {
	case SandboxStopReasonExpired:
		return true
	case SandboxStopReasonFailed:
		return true
	case SandboxStopReasonIdle:
		return true
	case SandboxStopReasonStopped:
		return true
	default:
		return false
	}
}

// Defines values for TaskObject.
const (
	TaskObjectTask TaskObject = "task"
)

// Valid indicates whether the value is a known member of the TaskObject enum.
func (e TaskObject) Valid() bool {
	switch e {
	case TaskObjectTask:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusDone    TaskStatus = "done"
	TaskStatusFailed  TaskStatus = "failed"
	TaskStatusPending TaskStatus = "pending"
	TaskStatusRunning TaskStatus = "running"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusDone:
		return true
	case TaskStatusFailed:
		return true
	case TaskStatusPending:
		return true
	case TaskStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for TenantObject.
const (
	TenantObjectTenant TenantObject = "tenant"
)

// Valid indicates whether the value is a known member of the TenantObject enum.
func (e TenantObject) Valid() bool {
	switch e {
	case TenantObjectTenant:
		return true
	default:
		return false
	}
}

// Defines values for TenantFullPolicy.
const (
	Evict    TenantFullPolicy = "evict"
	Preserve TenantFullPolicy = "preserve"
)

// Valid indicates whether the value is a known member of the TenantFullPolicy enum.
func (e TenantFullPolicy) Valid() bool {
	switch e {
	case Evict:
		return true
	case Preserve:
		return true
	default:
		return false
	}
}

// Defines values for TenantListObject.
const (
	List TenantListObject = "list"
)

// Valid indicates whether the value is a known member of the TenantListObject enum.
func (e TenantListObject) Valid() bool {
	switch e {
	case List:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code A stable, machine-readable identifier. Switch on this. The message is
	// for humans and may be reworded at any time.
	Code string `json:"code"`

	// Message A human-readable explanation. Never parse it.
	Message string `json:"message"`

	// Param Which request field was at fault, when one was.
	Param *string `json:"param,omitempty"`

	// RequestId Quote this when reporting a problem.
	RequestId *string `json:"request_id,omitempty"`

	// Type The class of error, which determines what a client should *do*:
	//
	// - `invalid_request_error` — the request is wrong. Retrying it unchanged
	//   will fail identically.
	// - `authentication_error` — the token is missing or wrong.
	// - `capacity_error` — no room right now. Retrying later may work; a task
	//   would not have failed at all.
	// - `idempotency_error` — an Idempotency-Key was reused with a different
	//   body.
	// - `api_error` — our fault. Safe to retry with the same Idempotency-Key.
	Type ErrorType `json:"type"`
}

// ErrorEnvelope The body of every non-2xx reply.
type ErrorEnvelope struct {
	Error Error `json:"error"`
}

// ErrorType The class of error, which determines what a client should *do*:
//
//   - `invalid_request_error` — the request is wrong. Retrying it unchanged
//     will fail identically.
//   - `authentication_error` — the token is missing or wrong.
//   - `capacity_error` — no room right now. Retrying later may work; a task
//     would not have failed at all.
//   - `idempotency_error` — an Idempotency-Key was reused with a different
//     body.
//   - `api_error` — our fault. Safe to retry with the same Idempotency-Key.
type ErrorType string

// Execution defines model for Execution.
type Execution struct {
	Args       *[]string `json:"args,omitempty"`
	Cmd        string    `json:"cmd"`
	Created    time.Time `json:"created"`
	DurationMs *int      `json:"duration_ms,omitempty"`

	// Error Why the command could never start. Set only when status is `failed`.
	Error    *string         `json:"error,omitempty"`
	ExitCode *int            `json:"exit_code,omitempty"`
	Finished *time.Time      `json:"finished,omitempty"`
	Id       string          `json:"id"`
	Object   ExecutionObject `json:"object"`
	Sandbox  string          `json:"sandbox"`

	// Signal The signal that killed it, if one did.
	Signal *string `json:"signal,omitempty"`

	// Status Outcomes that all look like failure but are not, and a caller must tell
	// apart:
	//
	// - `running` — still going.
	// - `exited` — your code ran to completion. `exit_code` is its own verdict.
	// - `timed_out` — it exceeded its timeout and we killed it.
	// - `canceled` — you cancelled it.
	// - `vanished` — **we took the VM away.** Your code did not fail.
	// - `failed` — the command could never start, e.g. no such binary.
	Status          ExecutionStatus `json:"status"`
	Stderr          string          `json:"stderr"`
	StderrTruncated *bool           `json:"stderr_truncated,omitempty"`
	Stdout          string          `json:"stdout"`

	// StdoutTruncated Output exceeded the retention cap and the oldest bytes were dropped.
	// The *tail* is kept, because that is where a traceback is. Never
	// silently truncated: a partial log that looks complete is worse than
	// no log.
	StdoutTruncated *bool `json:"stdout_truncated,omitempty"`
}

// ExecutionObject defines model for Execution.Object.
type ExecutionObject string

// ExecutionCancelParams defines model for ExecutionCancelParams.
type ExecutionCancelParams struct {
	// Signal The signal to send. It reaches the whole process group.
	Signal *string `json:"signal,omitempty"`
}

// ExecutionCreateParams defines model for ExecutionCreateParams.
type ExecutionCreateParams struct {
	Args *[]string `json:"args,omitempty"`
	Cmd  string    `json:"cmd"`
	Cwd  *string   `json:"cwd,omitempty"`

	// Env Merged over the sandbox's env; these win. Write-only.
	Env *map[string]string `json:"env,omitempty"`

	// Stdin Written to the process, then closed.
	Stdin *[]byte `json:"stdin,omitempty"`

	// TimeoutSeconds Kills the process group when exceeded.
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`
}

// ExecutionList defines model for ExecutionList.
type ExecutionList struct {
	Data []Execution `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool                `json:"has_more"`
	Object  ExecutionListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// ExecutionListObject defines model for ExecutionList.Object.
type ExecutionListObject string

// ExecutionStatus Outcomes that all look like failure but are not, and a caller must tell
// apart:
//
// - `running` — still going.
// - `exited` — your code ran to completion. `exit_code` is its own verdict.
// - `timed_out` — it exceeded its timeout and we killed it.
// - `canceled` — you cancelled it.
// - `vanished` — **we took the VM away.** Your code did not fail.
// - `failed` — the command could never start, e.g. no such binary.
type ExecutionStatus string

// File defines model for File.
type File struct {
	Object    FileObject `json:"object"`
	Path      string     `json:"path"`
	SizeBytes int        `json:"size_bytes"`
}

// FileObject defines model for File.Object.
type FileObject string

// FileCreateParams defines model for FileCreateParams.
type FileCreateParams struct {
	// Content The file's bytes, base64 encoded so binary survives the trip.
	Content []byte `json:"content"`

	// Path Absolute path inside the sandbox. Parent directories are created.
	Path string `json:"path"`
}

// Frame One event in an execution's stream, sent as an SSE data payload.
type Frame struct {
	// Data The chunk, base64 so binary output survives the trip.
	Data     *[]byte     `json:"data,omitempty"`
	ExitCode *int        `json:"exit_code,omitempty"`
	Message  *string     `json:"message,omitempty"`
	Object   FrameObject `json:"object"`
	Pid      *int        `json:"pid,omitempty"`
	Signal   *string     `json:"signal,omitempty"`
	TimedOut *bool       `json:"timed_out,omitempty"`
	Type     FrameType   `json:"type"`
}

// FrameObject defines model for Frame.Object.
type FrameObject string

// FrameType defines model for Frame.Type.
type FrameType string

// Health defines model for Health.
type Health struct {
	Object  HealthObject `json:"object"`
	Ok      bool         `json:"ok"`
	Version string       `json:"version"`
}

// HealthObject defines model for Health.Object.
type HealthObject string

// Image defines model for Image.
type Image struct {
	Arch      *string     `json:"arch,omitempty"`
	Id        string      `json:"id"`
	Language  string      `json:"language"`
	Object    ImageObject `json:"object"`
	SizeBytes *int        `json:"size_bytes,omitempty"`
}

// ImageObject defines model for Image.Object.
type ImageObject string

// ImageList defines model for ImageList.
type ImageList struct {
	Data []Image `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool            `json:"has_more"`
	Object  ImageListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// ImageListObject defines model for ImageList.Object.
type ImageListObject string

// ListEnvelope defines model for ListEnvelope.
type ListEnvelope struct {
	Data []map[string]interface{} `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool               `json:"has_more"`
	Object  ListEnvelopeObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// ListEnvelopeObject defines model for ListEnvelope.Object.
type ListEnvelopeObject string

// Queue defines model for Queue.
type Queue struct {
	// Busy This node's slots currently running something.
	Busy   int `json:"busy"`
	Done   int `json:"done"`
	Failed int `json:"failed"`

	// Leased Held by a worker somewhere in the fleet.
	Leased int         `json:"leased"`
	Object QueueObject `json:"object"`

	// OldestPendingMs How long the head of the queue has waited. This is the number that
	// says whether the fleet is big enough.
	OldestPendingMs int `json:"oldest_pending_ms"`
	Pending         int `json:"pending"`

	// Slots This node's slots. Not the fleet's.
	Slots int `json:"slots"`
}

// QueueObject defines model for Queue.Object.
type QueueObject string

// Sandbox defines model for Sandbox.
type Sandbox struct {
	Created time.Time `json:"created"`

	// Expires When the TTL kills it, whatever it is doing.
	Expires time.Time `json:"expires"`
	Id      string    `json:"id"`
	Image   string    `json:"image"`
	MemMib  *int      `json:"mem_mib,omitempty"`

	// Network Whether filtered egress is on.
	Network *bool         `json:"network,omitempty"`
	Object  SandboxObject `json:"object"`
	State   SandboxState  `json:"state"`

	// Stats What a sandbox has consumed. Cumulative since boot, so a biller must
	// diff two samples: booting alone costs a couple of CPU-seconds, and
	// cumulative idle is meaningless for a sandbox's first seconds.
	Stats Stats `json:"stats"`

	// StopReason Set once the sandbox is stopped.
	StopReason *SandboxStopReason `json:"stop_reason,omitempty"`
	Stopped    *time.Time         `json:"stopped,omitempty"`

	// Storage Where this sandbox's files persist, when the node has object storage
	// configured. Absent when it does not.
	Storage *SandboxStorage `json:"storage,omitempty"`
	Vcpus   *int            `json:"vcpus,omitempty"`
}

// SandboxObject defines model for Sandbox.Object.
type SandboxObject string

// SandboxCreateParams defines model for SandboxCreateParams.
type SandboxCreateParams struct {
	// CpuCores A hard CPU ceiling; may be fractional. 0.5 means half a core, enforced.
	CpuCores *float64 `json:"cpu_cores,omitempty"`
	DiskBps  *int     `json:"disk_bps,omitempty"`
	DiskIops *int     `json:"disk_iops,omitempty"`
	DiskMib  *int     `json:"disk_mib,omitempty"`

	// Env Injected into every execution in this sandbox. An execution's own
	// env wins where they overlap.
	//
	// Write-only. These usually carry credentials, so they are never
	// logged and no endpoint returns them. They are applied by the host on
	// each execution rather than written into the guest's filesystem,
	// where anything inside could read them long after the command that
	// needed them.
	Env *map[string]string `json:"env,omitempty"`

	// IdleSeconds Reclaim after this long with nothing running. Negative disables it.
	IdleSeconds *int `json:"idle_seconds,omitempty"`

	// Image The language image.
	Image  string `json:"image"`
	MemMib *int   `json:"mem_mib,omitempty"`

	// Network Filtered egress. The public internet is reachable; every private
	// range, link-local and the cloud metadata endpoint are not.
	Network *bool `json:"network,omitempty"`

	// NetworkBps Caps bandwidth both ways, in bytes per second. Worth setting even
	// when CPU is capped: a sandbox pinned to a quarter core can still
	// saturate the host's uplink, and the first you hear of it is the
	// abuse complaint.
	NetworkBps *int `json:"network_bps,omitempty"`

	// Storage Options for this sandbox's storage mount. The namespace is never set
	// here — it comes from your API key. Only the read/write posture is
	// yours to choose, and only to tighten.
	Storage *SandboxStorageParams `json:"storage,omitempty"`

	// TtlSeconds Maximum lifetime. The sandbox is killed when it elapses.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
	Vcpus      *int `json:"vcpus,omitempty"`
}

// SandboxList defines model for SandboxList.
type SandboxList struct {
	Data []Sandbox `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool              `json:"has_more"`
	Object  SandboxListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// SandboxListObject defines model for SandboxList.Object.
type SandboxListObject string

// SandboxState defines model for SandboxState.
type SandboxState string

// SandboxStopReason Why a sandbox stopped. `stopped` means you asked; the rest happened to
// it, and only `failed` means something went wrong.
type SandboxStopReason string

// SandboxStorage A sandbox's view of object storage. Files written here outlive the
// sandbox and are reachable by every sandbox in the same `namespace`, which
// is how state is carried from one run to the next.
type SandboxStorage struct {
	// MaxBytes Your tenant's total storage cap in bytes, or 0 for unlimited. This is
	// the limit your writes are measured against; it is set by an admin.
	MaxBytes *int64 `json:"max_bytes,omitempty"`

	// MountPath Where storage is mounted inside the guest, e.g. `/mnt/storage`. This
	// is a directory in your own sandbox, not a namespace, so choosing it
	// reaches nobody else's files. Defaults to `/mnt/storage`.
	MountPath *string `json:"mount_path,omitempty"`

	// Namespace The tenant your files live under, derived from your API key. It is
	// yours and stable: write a file today, read it from another sandbox
	// tomorrow. You cannot choose it — that is what stops one tenant from
	// naming another's.
	Namespace string `json:"namespace"`

	// Policy What a write does when the cap is reached. Absent when there is no cap.
	Policy *TenantFullPolicy `json:"policy,omitempty"`

	// ReadOnly Whether this sandbox may write, or only read.
	ReadOnly bool `json:"read_only"`
}

// SandboxStorageParams What a create request may say about storage, which is very little.
type SandboxStorageParams struct {
	// MountPath Where to mount storage inside the guest. An absolute, clean path using
	// only letters, digits and `_-./`; it names a directory in your own
	// sandbox and cannot reach another tenant's files. Defaults to
	// `/mnt/storage`.
	MountPath *string `json:"mount_path,omitempty"`

	// ReadOnly Mount storage read-only for this sandbox even if the key could write.
	// It can only tighten: a read-only key stays read-only whatever you set
	// here. Useful for a run that should read shared state but never touch it.
	ReadOnly *bool `json:"read_only,omitempty"`
}

// Stats What a sandbox has consumed. Cumulative since boot, so a biller must
// diff two samples: booting alone costs a couple of CPU-seconds, and
// cumulative idle is meaningless for a sandbox's first seconds.
type Stats struct {
	// ActiveCpuMs CPU actually burned. **This is the billable number.** A sandbox
	// blocked on I/O bills nearly nothing: three seconds asleep costs
	// about 15ms of this.
	ActiveCpuMs int `json:"active_cpu_ms"`

	// IdleMs `wall_ms` minus `active_cpu_ms`: existing but doing nothing. Zero
	// when a multi-vCPU sandbox burns more CPU than wall-clock.
	IdleMs             int `json:"idle_ms"`
	MemoryCurrentBytes int `json:"memory_current_bytes"`

	// MemoryPeakBytes The high-water mark, which is what a memory limit must be sized against.
	MemoryPeakBytes int `json:"memory_peak_bytes"`

	// WallMs How long the sandbox has existed.
	WallMs int `json:"wall_ms"`
}

// Task defines model for Task.
type Task struct {
	ActiveCpuMs *int `json:"active_cpu_ms,omitempty"`

	// Attempts How many tries it took. Retries are for nodes dying, not for code
	// failing: a task whose process exits non-zero is never retried, or a
	// caller's bug would be run repeatedly and billed for each attempt.
	Attempts *int       `json:"attempts,omitempty"`
	Created  *time.Time `json:"created,omitempty"`

	// Error An infrastructure failure. Distinct from a non-zero exit, which is
	// the caller's own code and not a failure of ours.
	Error           *string    `json:"error,omitempty"`
	ExitCode        *int       `json:"exit_code,omitempty"`
	Finished        *time.Time `json:"finished,omitempty"`
	Id              string     `json:"id"`
	MemoryPeakBytes *int       `json:"memory_peak_bytes,omitempty"`
	Object          TaskObject `json:"object"`
	Started         *time.Time `json:"started,omitempty"`

	// Status - `pending` — waiting for a slot anywhere in the fleet.
	// - `running` — a node holds it.
	// - `done` — it ran. `exit_code` is your code's own verdict, and a
	//   non-zero one is still `done`.
	// - `failed` — **our** failure: no node could run it, after its attempts
	//   ran out.
	Status TaskStatus `json:"status"`
	Stderr *string    `json:"stderr,omitempty"`
	Stdout *string    `json:"stdout,omitempty"`
}

// TaskObject defines model for Task.Object.
type TaskObject string

// TaskCreateParams defines model for TaskCreateParams.
type TaskCreateParams struct {
	Args     *[]string `json:"args,omitempty"`
	Cmd      string    `json:"cmd"`
	CpuCores *float64  `json:"cpu_cores,omitempty"`

	// Env Write-only.
	Env *map[string]string `json:"env,omitempty"`

	// Files Written into the sandbox before the command runs, keyed by path.
	Files *map[string][]byte `json:"files,omitempty"`
	Image string             `json:"image"`

	// MaxAttempts How many times a node may try this before it is failed for good. Two
	// means one retry: enough to survive a node dying, few enough that a
	// task which reliably kills its worker cannot cycle the fleet forever.
	MaxAttempts *int  `json:"max_attempts,omitempty"`
	MemMib      *int  `json:"mem_mib,omitempty"`
	Network     *bool `json:"network,omitempty"`

	// Priority Scheduling priority, 0 to 10. Higher runs first; equal priorities are
	// FIFO, which is the guarantee callers actually reason about. It orders
	// the queue within what a node can fit: among the tasks a node has room
	// for, the highest priority is taken first, so a high-priority task that
	// does not fit yields to a lower one that does rather than blocking it.
	Priority       *int `json:"priority,omitempty"`
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`
	Vcpus          *int `json:"vcpus,omitempty"`
}

// TaskStatus - `pending` — waiting for a slot anywhere in the fleet.
//   - `running` — a node holds it.
//   - `done` — it ran. `exit_code` is your code's own verdict, and a
//     non-zero one is still `done`.
//   - `failed` — **our** failure: no node could run it, after its attempts
//     ran out.
type TaskStatus string

// Tenant defines model for Tenant.
type Tenant struct {
	// Id The tenant namespace this policy applies to.
	Id string `json:"id"`

	// MaxBytes The tenant's total storage cap, in bytes. 0 means unlimited.
	MaxBytes int64        `json:"max_bytes"`
	Object   TenantObject `json:"object"`

	// Policy What a write does when a tenant is at its cap.
	//
	// - `preserve` — reject the write and keep what is stored. For data that
	//   matters more than the next write: an audit trail, a paid-for dataset.
	// - `evict` — delete the oldest objects until the write fits. For a cache
	//   or scratch space, where the newest data is the point. It deletes data,
	//   irreversibly, which is why it is never the default.
	Policy TenantFullPolicy `json:"policy"`

	// UsageBytes Bytes currently stored, read from the object store on retrieve. Absent
	// on the reply to an update, which does not stop to scan the bucket.
	UsageBytes *int64 `json:"usage_bytes,omitempty"`
}

// TenantObject defines model for Tenant.Object.
type TenantObject string

// TenantFullPolicy What a write does when a tenant is at its cap.
//
//   - `preserve` — reject the write and keep what is stored. For data that
//     matters more than the next write: an audit trail, a paid-for dataset.
//   - `evict` — delete the oldest objects until the write fits. For a cache
//     or scratch space, where the newest data is the point. It deletes data,
//     irreversibly, which is why it is never the default.
type TenantFullPolicy string

// TenantList defines model for TenantList.
type TenantList struct {
	Data []Tenant `json:"data"`

	// HasMore Whether more objects exist past this page. Page on with
	// `starting_after` set to the last ID in `data`.
	HasMore bool             `json:"has_more"`
	Object  TenantListObject `json:"object"`

	// Url The endpoint this list came from.
	Url string `json:"url"`
}

// TenantListObject defines model for TenantList.Object.
type TenantListObject string

// TenantUpdateParams defines model for TenantUpdateParams.
type TenantUpdateParams struct {
	// MaxBytes The tenant's total storage cap, in bytes. 0 means unlimited.
	MaxBytes int64 `json:"max_bytes"`

	// Policy What a write does when a tenant is at its cap.
	//
	// - `preserve` — reject the write and keep what is stored. For data that
	//   matters more than the next write: an audit trail, a paid-for dataset.
	// - `evict` — delete the oldest objects until the write fits. For a cache
	//   or scratch space, where the newest data is the point. It deletes data,
	//   irreversibly, which is why it is never the default.
	Policy TenantFullPolicy `json:"policy"`
}

// EndingBefore defines model for EndingBefore.
type EndingBefore = string

// ExecutionId defines model for ExecutionId.
type ExecutionId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// SandboxId defines model for SandboxId.
type SandboxId = string

// StartingAfter defines model for StartingAfter.
type StartingAfter = string

// TaskId defines model for TaskId.
type TaskId = string

// ApiError The body of every non-2xx reply.
type ApiError = ErrorEnvelope

// CapacityExhausted The body of every non-2xx reply.
type CapacityExhausted = ErrorEnvelope

// Conflict The body of every non-2xx reply.
type Conflict = ErrorEnvelope

// Forbidden The body of every non-2xx reply.
type Forbidden = ErrorEnvelope

// InvalidRequest The body of every non-2xx reply.
type InvalidRequest = ErrorEnvelope

// NotFound The body of every non-2xx reply.
type NotFound = ErrorEnvelope

// QueueUnreachable The body of every non-2xx reply.
type QueueUnreachable = ErrorEnvelope

// Unauthorized The body of every non-2xx reply.
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListSandboxesParams defines parameters for ListSandboxes.
type ListSandboxesParams struct {
	// Limit How many objects to return, 1–100.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter A cursor. Returns the page of objects immediately after this ID, which
	// is the ID of the last object on the previous page.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore A cursor, for paging backwards. Returns the page immediately before this
	// ID, which is the ID of the first object on the current page.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// State Only sandboxes in this state.
	State *SandboxState `form:"state,omitempty" json:"state,omitempty"`
}

// CreateSandboxParams defines parameters for CreateSandbox.
type CreateSandboxParams struct {
	// IdempotencyKey Makes a retry safe. A request that never got its reply -- a timeout, a
	// dropped connection -- cannot be known to have failed, so the only sane
	// move is to retry it; without a key, that retry runs the work twice.
	//
	// The first request with a given key is executed and its reply recorded.
	// Any later request with the same key replays that reply, without doing
	// the work again. Keys are held for 24 hours and are scoped to the token.
	//
	// Reusing a key with a *different* request body is an `idempotency_error`:
	// it means the client believes it is retrying something it is not.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	// Limit How many objects to return, 1–100.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter A cursor. Returns the page of objects immediately after this ID, which
	// is the ID of the last object on the previous page.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore A cursor, for paging backwards. Returns the page immediately before this
	// ID, which is the ID of the first object on the current page.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// CreateExecutionParams defines parameters for CreateExecution.
type CreateExecutionParams struct {
	// IdempotencyKey Makes a retry safe. A request that never got its reply -- a timeout, a
	// dropped connection -- cannot be known to have failed, so the only sane
	// move is to retry it; without a key, that retry runs the work twice.
	//
	// The first request with a given key is executed and its reply recorded.
	// Any later request with the same key replays that reply, without doing
	// the work again. Keys are held for 24 hours and are scoped to the token.
	//
	// Reusing a key with a *different* request body is an `idempotency_error`:
	// it means the client believes it is retrying something it is not.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RetrieveFileParams defines parameters for RetrieveFile.
type RetrieveFileParams struct {
	// Path Absolute path inside the sandbox.
	Path string `form:"path" json:"path"`
}

// CreateTaskParams defines parameters for CreateTask.
type CreateTaskParams struct {
	// IdempotencyKey Makes a retry safe. A request that never got its reply -- a timeout, a
	// dropped connection -- cannot be known to have failed, so the only sane
	// move is to retry it; without a key, that retry runs the work twice.
	//
	// The first request with a given key is executed and its reply recorded.
	// Any later request with the same key replays that reply, without doing
	// the work again. Keys are held for 24 hours and are scoped to the token.
	//
	// Reusing a key with a *different* request body is an `idempotency_error`:
	// it means the client believes it is retrying something it is not.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateSandboxJSONRequestBody defines body for CreateSandbox for application/json ContentType.
type CreateSandboxJSONRequestBody = SandboxCreateParams

// CreateExecutionJSONRequestBody defines body for CreateExecution for application/json ContentType.
type CreateExecutionJSONRequestBody = ExecutionCreateParams

// CancelExecutionJSONRequestBody defines body for CancelExecution for application/json ContentType.
type CancelExecutionJSONRequestBody = ExecutionCancelParams

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = FileCreateParams

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskCreateParams

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = TenantUpdateParams
