#!/bin/bash
# Reads a tar stream of a root filesystem on stdin and writes an ext4 image to
# /out/$OUT_NAME. Runs inside the packer container; see images/packer/Dockerfile.
#
# Environment:
#   OUT_NAME   filename to write under /out
#   SLACK_MB   free space to add on top of the measured contents
#   OWNER_UID  uid to chown the result to, so the host user owns its own build
#   OWNER_GID  gid to chown the result to
set -euo pipefail

readonly OUT_NAME="${OUT_NAME:?OUT_NAME is required}"
readonly SLACK_MB="${SLACK_MB:-256}"
readonly ROOTDIR=/rootfs

die() { echo "pack: error: $*" >&2; exit 1; }
log() { echo "pack: $*"; }

mkdir -p "$ROOTDIR"

log "unpacking"
# Ownership, permissions and setuid bits must survive: the guest's userland
# depends on them, and this container is root so they can be applied faithfully.
tar -xf - -C "$ROOTDIR" --same-owner --preserve-permissions --numeric-owner

# Docker synthesises these per-container. In a microVM the kernel and init
# provide them, so an inherited copy would shadow the real thing with a stale
# value.
rm -f "$ROOTDIR/etc/hostname" "$ROOTDIR/etc/resolv.conf" "$ROOTDIR/.dockerenv"

# Materialise the image's environment into the filesystem.
#
# A Dockerfile's ENV lines are container-runtime metadata: they live in the image
# *config*, not in any file, and Docker injects them when it starts a process.
# Nothing starts our processes but the guest kernel, which hands PID 1 an empty
# environment -- so without this every ENV in the Dockerfile is silently dead.
# That is not a small loss: PATH is where it lives, so `rustc` and `go` simply
# cannot be found, and the failure looks like a broken image rather than a
# missing variable.
if [ -n "${IMAGE_ENV:-}" ]; then
    mkdir -p "$ROOTDIR/etc/microvm"
    printf '%s\n' "$IMAGE_ENV" > "$ROOTDIR/etc/microvm/environment"
    chmod 0644 "$ROOTDIR/etc/microvm/environment"
    log "captured $(grep -c . "$ROOTDIR/etc/microvm/environment") environment variables from the image"
fi

# A rootfs with no init makes the kernel panic seconds into boot, with an error
# that points at the kernel rather than at the image. Fail here instead.
#
# The check cannot simply be `-e $ROOTDIR/sbin/init`: init is a symlink whose
# target is absolute (/sbin/microvm-agent), and an absolute target resolves
# against *this* container's root, not against $ROOTDIR. So verify the link
# exists as a link, then resolve it ourselves relative to the rootfs.
init_link="$ROOTDIR/sbin/init"
[ -L "$init_link" ] || [ -f "$init_link" ] || die "image has no /sbin/init"

init_target="$(readlink -f --no-newline "$init_link" 2>/dev/null || true)"
if [ -L "$init_link" ]; then
    raw="$(readlink "$init_link")"
    case "$raw" in
        /*) init_target="$ROOTDIR$raw" ;;                       # absolute: rebase onto the rootfs
        *)  init_target="$(dirname "$init_link")/$raw" ;;       # relative: already correct
    esac
fi
[ -f "$init_target" ] || die "/sbin/init points at ${init_target#$ROOTDIR}, which is missing from the image"
[ -x "$init_target" ] || die "/sbin/init target ${init_target#$ROOTDIR} is not executable"

used_mb="$(du -sm "$ROOTDIR" | cut -f1)"
size_mb="$((used_mb + SLACK_MB))"
log "contents ${used_mb}MB, allocating ${size_mb}MB"

readonly OUT="/out/$OUT_NAME"
rm -f "$OUT"

# -d populates from a directory, so no loop device and no mount is needed.
# ^has_journal: the image is mounted read-only in the guest and regenerated by
# this script, so a journal only costs space and write amplification.
mke2fs -q -F -t ext4 -b 4096 -O ^has_journal -d "$ROOTDIR" "$OUT" "${size_mb}M"

# Prove the image is consistent here, rather than discovering it during a boot
# that fails for reasons that look unrelated.
e2fsck -fp "$OUT" >/dev/null || die "generated filesystem is not clean"

# dm-verity: generate a Merkle hash tree over the finished image and record the
# root hash, so the daemon can boot it as a verified device that the kernel
# refuses to mount if a single block was altered.
#
# Opt-in (MICROVM_VERITY=1) because it needs a guest kernel with CONFIG_DM_VERITY
# and CONFIG_DM_INIT; images built without it have no sidecar and boot normally.
# The salt is pinned to 64 zero hex chars so the root hash is a deterministic
# function of the image content alone -- two byte-identical rootfs builds yield
# the same root hash, which is what keeps a shared image cache meaningful.
if [ "${MICROVM_VERITY:-0}" = "1" ]; then
  log "generating dm-verity hash tree"
  readonly VERITY_SALT="0000000000000000000000000000000000000000000000000000000000000000"
  [ ${#VERITY_SALT} -eq 64 ] || die "verity salt must be 64 hex chars"
  readonly HASH_OUT="$OUT.hash"
  readonly META_OUT="$OUT.verity"
  : > "$HASH_OUT"
  rm -f "$META_OUT"

  # --no-superblock: the hash tree starts at block 0 of the hash device, so the
  # daemon's dm table uses hash_start_block=0 -- no metadata block to skip.
  vs_out="$(veritysetup format \
    --no-superblock \
    --hash=sha256 \
    --data-block-size=4096 \
    --hash-block-size=4096 \
    --salt="$VERITY_SALT" \
    "$OUT" "$HASH_OUT")"

  root_hash="$(printf '%s\n' "$vs_out" | awk '/Root hash:/ {print $NF}')"
  [ -n "$root_hash" ] || die "veritysetup produced no root hash"

  # The image is a whole number of 4096-byte blocks (mke2fs -b 4096), so the data
  # block count is exact -- no need to trust veritysetup's stdout for it.
  img_bytes="$(stat -c %s "$OUT")"
  data_blocks=$(( img_bytes / 4096 ))

  cat > "$META_OUT" <<JSON
{
  "root_hash": "$root_hash",
  "salt": "$VERITY_SALT",
  "data_blocks": $data_blocks,
  "data_block_size": 4096,
  "hash_block_size": 4096,
  "hash_start_block": 0,
  "hash_algorithm": "sha256"
}
JSON
  log "verity root hash $root_hash ($data_blocks data blocks, hash tree $(du -h "$HASH_OUT" | cut -f1))"
fi

if [ -n "${OWNER_UID:-}" ] && [ -n "${OWNER_GID:-}" ]; then
  chown "$OWNER_UID:$OWNER_GID" "$OUT"
  [ -f "$OUT.hash" ] && chown "$OWNER_UID:$OWNER_GID" "$OUT.hash"
  [ -f "$OUT.verity" ] && chown "$OWNER_UID:$OWNER_GID" "$OUT.verity"
fi

log "wrote $OUT_NAME ($(du -h "$OUT" | cut -f1))"
